<?php
/**
 * @file
 * Client-side data space.
 */

/**
 * Implements hook_help().
 */
function semi_anonymous_help($path, $arg) {
  switch ($path) {
    case 'admin/help#semi_anonymous':
      return t("Provide standardized space, and will handle stashing for client-side tracking and reactions to user behavior. This module is particularly intended for folks who use Varnish caching and have very little server-side interaction for anonymous users.");
  }
}


/**
 * Implements hook_menu().
 */
function semi_anonymous_menu() {
  $items['admin/config/system/semi-anonymous'] = array(
    'title' => 'Semi Anonymous',
    'description' => 'Provide standardized space and adds page meta data client-side use.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('semi_anonymous_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'semi_anonymous.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_preprocess_HOOK().
 * Outputs meta data details of the page, for use with local storage.
 */
function semi_anonymous_preprocess_html(&$variables) {
  $ouput_data = array();
  $m = 'semi_anonymous_';

  // Add basic assets.
  if (variable_get($m . 'include', TRUE)) {
    // JSON2.
    if (function_exists('libraries_load') && libraries_load('json2')) {
      // You have Libraries 2.0 and some module registered this one.
    }
    else {
      $json_path = libraries_get_path('json2');
      if (!empty($json_path) && file_exists($json_path . '/json2.js')) {
        drupal_add_js($json_path . '/json2.js');
      }
    }
    // jStorage.
    if (function_exists('libraries_load') && libraries_load('jstorage')) {
      // You have Libraries 2.0 and some module registered this one.
    }
    else {
      $json_path = libraries_get_path('jstorage');
      if (!empty($json_path) && file_exists($json_path . '/jstorage.js')) {
        drupal_add_js($json_path . '/jstorage.min.js');
      }
    }
  }

  // Allow for tracking.
  if (module_exists('datalayer') && (variable_get($m . 'track_browsing', FALSE))) {

    // Output library settings.
    $settings = array(
      'tracking' => true,
      'track_term_hits' => variable_get($m . 'track_term_hits', FALSE),
      'track_browsing_extent' => variable_get($m . 'track_browsing_extent', 25),
    );
    $output = !empty($settings) ? drupal_json_encode($settings) : '';
    $render = array(
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => 'semiAnon = [' . $output . '];',
      '#attributes' => array(
        'type' => 'text/javascript',
      ),
    );
    drupal_add_html_head($render, 'datalayer_meta');

    // Add tracking library.
    drupal_add_js(drupal_get_path('module', 'semi_anonymous') . '/js/semi_anonymous.tracking.js');
  }

  // Add user origin library.
  if (variable_get($m . 'store_user_origins', TRUE)) {
    drupal_add_js(drupal_get_path('module', 'semi_anonymous') . '/js/semi_anonymous.users.js');
  }
}

// @todo Place checkbox on output Data Layer fields for tracking inclusion.
